### ISSUE TITLE
`hrea_observation.dna` doesn't exist on the release page

### ISSUE THREAD

**Issue by weswalla** [neighbour-hoods/timetracking-applet#2]
the npm script `"download-hrea-obs"` tries to download `hrea_observation.dna` from https://github.com/h-REA/hREA/releases/download/happ-0.1.1-beta/hrea_observation.dna but I don't see that file in the release: https://github.com/h-REA/hREA/releases

**Comment by pospi** [comment]
Oh yeah, forgot to mention that sorry! You can update hREA and build one locally if you feel comfortable. But there are some upstream bugs in Nix to resolve before we can get a build up on Github https://github.com/h-REA/hREA/issues/380

**Comment by pospi** [comment]
Package scripts have been updated to reference https://github.com/h-REA/hREA/releases/tag/happ-0.1.1-beta_republish
